# Basic site configuration
base_url = "https://h3samayoa.github.io"
title = "Vocabulary List"
description = "A simple vocabulary list with LaTeX equations and images"

# Enable KaTeX for LaTeX rendering
[extra]
katex_enable = true
katex_auto_render = true

# Set up Markdown rendering
[markdown]
highlight_code = false
external_links_target_blank = true

# Set taxonomies for organization if needed
taxonomies = [
    {name = "categories", feed = true, paginate_by = 50},
    {name = "tags", feed = true, paginate_by = 50},
]

# Section options - all vocab words on single page
[extra.sections.vocab]
paginate_by = 0  # Disable pagination to have all words on one page